sprite[RIGHT]=spr_shadowcreature_body_holding
sprite[UP]=spr_shadowcreature_body_holding
sprite[DOWN]=spr_shadowcreature_body_holding
sprite[LEFT]=spr_shadowcreature_body_holding

sprite[WALKING_RIGHT]=spr_shadowcreature_body_holding
sprite[WALKING_UP]=spr_shadowcreature_body_holding
sprite[WALKING_DOWN]=spr_shadowcreature_body_holding
sprite[WALKING_LEFT]=spr_shadowcreature_body_holding
sprite[ATTACKING_RIGHT]=spr_shadowcreature_body_holding

sprite[HURT_RIGHT]=spr_shadowcreature_body_holding
sprite[VICTORY]=spr_shadowcreature_body_holding
sprite[DEFEAT]=spr_shadowcreature_body_holding

sprite[JUMPING]=spr_shadowcreature_body_holding

sprite[BTLINTRO1]=spr_shadowcreature_body
sprite[BTLINTRO2]=spr_shadowcreature_body
